//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.05 at 08:28:30 PM EEST 
//


package lt.viko.eif.tviliusis.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for categories complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="categories"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="categorieName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="components" type="{http://spring.io/guides/gs-producing-web-service}components" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "categories", propOrder = {
    "id",
    "categorieName",
    "components"
})
public class Categories {

    protected int id;
    @XmlElement(required = true)
    protected String categorieName;
    protected List<Components> components;

    public Categories(int id, String categorieName, List<Components> components) {
        this.id = id;
        this.categorieName = categorieName;
        this.components = components;
    }

    public Categories() {
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the categorieName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategorieName() {
        return categorieName;
    }

    /**
     * Sets the value of the categorieName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategorieName(String value) {
        this.categorieName = value;
    }

    /**
     * Gets the value of the components property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the components property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponents().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Components }
     * 
     * 
     */
    public List<Components> getComponents() {
        if (components == null) {
            components = new ArrayList<Components>();
        }
        return this.components;
    }

    public void setComponents(List<Components> components) {
        this.components = components;

    }

}
