
package lt.viko.eif.tviliusis;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShopPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShopPort {


    /**
     * 
     * @param changeUserRequest
     * @return
     *     returns lt.viko.eif.tviliusis.ChangeUserResponse
     */
    @WebMethod
    @WebResult(name = "changeUserResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "changeUserResponse")
    public ChangeUserResponse changeUser(
        @WebParam(name = "changeUserRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "changeUserRequest")
        ChangeUserRequest changeUserRequest);

    /**
     * 
     * @param deleteComponentRequest
     * @return
     *     returns lt.viko.eif.tviliusis.DeleteComponentResponse
     */
    @WebMethod
    @WebResult(name = "deleteComponentResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteComponentResponse")
    public DeleteComponentResponse deleteComponent(
        @WebParam(name = "deleteComponentRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteComponentRequest")
        DeleteComponentRequest deleteComponentRequest);

    /**
     * 
     * @param getShippingRequest
     * @return
     *     returns lt.viko.eif.tviliusis.GetShippingResponse
     */
    @WebMethod
    @WebResult(name = "getShippingResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getShippingResponse")
    public GetShippingResponse getShipping(
        @WebParam(name = "getShippingRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getShippingRequest")
        GetShippingRequest getShippingRequest);

    /**
     * 
     * @param addComponentRequest
     * @return
     *     returns lt.viko.eif.tviliusis.AddComponentResponse
     */
    @WebMethod
    @WebResult(name = "addComponentResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addComponentResponse")
    public AddComponentResponse addComponent(
        @WebParam(name = "addComponentRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "addComponentRequest")
        AddComponentRequest addComponentRequest);

    /**
     * 
     * @param getOrderPriceRequest
     * @return
     *     returns lt.viko.eif.tviliusis.GetOrderPriceResponse
     */
    @WebMethod
    @WebResult(name = "getOrderPriceResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getOrderPriceResponse")
    public GetOrderPriceResponse getOrderPrice(
        @WebParam(name = "getOrderPriceRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getOrderPriceRequest")
        GetOrderPriceRequest getOrderPriceRequest);

    /**
     * 
     * @param getAllAccountRequest
     * @return
     *     returns lt.viko.eif.tviliusis.GetAllAccountResponse
     */
    @WebMethod
    @WebResult(name = "getAllAccountResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getAllAccountResponse")
    public GetAllAccountResponse getAllAccount(
        @WebParam(name = "getAllAccountRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getAllAccountRequest")
        GetAllAccountRequest getAllAccountRequest);

    /**
     * 
     * @param deleteShippingRequest
     * @return
     *     returns lt.viko.eif.tviliusis.DeleteShippingResponse
     */
    @WebMethod
    @WebResult(name = "deleteShippingResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteShippingResponse")
    public DeleteShippingResponse deleteShipping(
        @WebParam(name = "deleteShippingRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "deleteShippingRequest")
        DeleteShippingRequest deleteShippingRequest);

}
